<li class="dropdown user user-menu">
 <!-- Menu Toggle Button -->
 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <!-- The user image in the navbar-->
    <img src="/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
    <!-- hidden-xs hides the username on small devices so only the image appears. -->
    <span class="hidden-xs"><?php echo $this->adminInfo->user_name; ?></span>
 </a>
 <ul class="dropdown-menu">
    <!-- The user image in the menu -->
    <li class="user-header">
       <img src="/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
       <p>
          <?php echo $this->adminInfo->user_name; ?> - admin
          <!-- <small>Member since Nov. 2012</small> -->
       </p>
    </li>
    <!-- Menu Body -->
    <li class="user-body">
       <div class="col-xs-4 text-center">
          <a href="#">Followers</a>
       </div>
       <div class="col-xs-4 text-center">
          <a href="#">Sales</a>
       </div>
       <div class="col-xs-4 text-center">
          <a href="#">Friends</a>
       </div>
    </li>
    <!-- Menu Footer-->
    <li class="user-footer">
       <div class="pull-left">
          <a href="#" class="btn btn-default btn-flat">Change password</a>
       </div>
       <div class="pull-right">
          <a href="/admin/auth/logout" class="btn btn-default btn-flat">Sign out</a>
       </div>
    </li>
 </ul>
</li>